services:
  postgres:
    image: postgres:latest
    container_name: hotel-checkin-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hotel_checkin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./hotel-checkin-backend
    container_name: hotel-checkin-backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hotel_checkin
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    restart: always

  frontend:
    build: ./hotel-checkin-frontend
    container_name: hotel-checkin-frontend
    ports:
      - "4200:4200"  # Agora mapeamos a porta do Angular
    depends_on:
      - backend
    volumes:
      - ./hotel-checkin-frontend:/app
      - /app/node_modules
    command: ["npm", "run", "start", "--", "--host", "0.0.0.0", "--port", "4200"]
    restart: always


volumes:
  postgres_data:
